name: CWD
version: ${project.version}
main: me.mintnetwork.Main
api-version: 1.17
authors: [ ElectricKiwi ]
commands:
  givewands:
    description: gives you the wand
  test:
    description: test!
  assignteams:
    description: admin command to assign teams for game
  class:
    description: A command to select your class
  start:
    description: starts the game
