name: CWD
version: ${project.version}
main: me.mintnetwork.Main
api-version: 1.16
authors: [ ElectricKiwi ]
commands:
  givewands:
    description: gives you the wand
  test:
    description: test!
  assign:
    description: admin command to assign teams for game
